name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Updated to Node.js 18

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }} # Use the secret for authentication
        run: |
          npx firebase-tools@latest deploy --only hosting --project weather-c8045 --token $FIREBASE_TOKEN --json
